# Generated by Django 4.2.3 on 2023-07-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_city_customer_pin_state_orderedplaced_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='city',
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='village',
            name='pin',
        ),
        migrations.RenameField(
            model_name='orderedplaced',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pincode',
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='totalAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderedplaced',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.state'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Pin',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
    ]
