# Generated by Django 4.2.3 on 2023-07-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_pin_city_alter_village_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedplaced',
            old_name='name',
            new_name='CustomerName',
        ),
        migrations.RemoveField(
            model_name='orderedplaced',
            name='customer',
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='paymentMethod',
            field=models.CharField(default='Cash on Delivery', max_length=255),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderedplaced',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.state'),
        ),
        migrations.AlterField(
            model_name='orderedplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('packed', 'packed'), ('Delivered', 'Delivered'), ('on the way', 'on the way'), ('cancel', 'cancel')], default='pending', max_length=50),
        ),
    ]
