# Generated by Django 4.2.2 on 2023-08-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_name_orderedplaced_customername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedplaced',
            old_name='CustomerName',
            new_name='customerName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderedplaced',
            name='phone',
            field=models.BigIntegerField(default='0000000000'),
        ),
        migrations.AlterField(
            model_name='orderedplaced',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orderedplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('packed', 'packed'), ('Delivered', 'Delivered'), ('on the way', 'on the way'), ('cancel', 'cancel')], default='Accepted', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('man', 'Man'), ('women', 'Woman'), ('kids', 'Kids'), ('electronics', 'Electronics'), ('mobiles', 'Mobiles')], default='man', max_length=15),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
