# Generated by Django 4.2.2 on 2023-08-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_customername_orderedplaced_customername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedplaced',
            old_name='totalAmount',
            new_name='amount',
        ),
    ]
