# Generated by Django 4.2.2 on 2023-08-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_orderedplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedplaced',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('packed', 'Packed'), ('delivered', 'Delivered'), ('on the way', 'On the way'), ('canceled', 'Canceled')], default='Accepted', max_length=50),
        ),
    ]
