# Generated by Django 4.2.3 on 2023-08-04 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_coupon_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
