# Generated by Django 4.2.3 on 2023-08-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_coupon_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
    ]
